# Generated by Django 3.2.9 on 2021-12-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.IntegerField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=50)),
                ('is_opioid', models.BooleanField()),
            ],
            options={
                'db_table': 'drug',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('npi', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('credential', models.CharField(blank=True, max_length=25)),
                ('specialty', models.CharField(max_length=50)),
                ('is_opioid_prescriber', models.BooleanField()),
                ('total_prescriptions', models.IntegerField()),
            ],
            options={
                'db_table': 'prescriber',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_abbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=15)),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='PrescriberDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opusapp.drug')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opusapp.prescriber')),
            ],
            options={
                'db_table': 'prescriber_drug',
            },
        ),
        migrations.AddField(
            model_name='prescriber',
            name='prescriber_drugs',
            field=models.ManyToManyField(through='opusapp.PrescriberDrug', to='opusapp.Drug'),
        ),
        migrations.AddField(
            model_name='prescriber',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='opusapp.state'),
        ),
    ]
